language: python
python:
  - 2.7

env:
  - TARGET=html TDB_TYPE=sqlite PYFARM_DATABASE_URI="sqlite:///:memory:" PYFARM_CONFIG="debug"

install:
  - python setup.py install

script:
  - pip freeze
  - make $TARGET
